const outcomes={
  TRANSIENT:{title:'Retry with backoff',reasonCode:'RETRYABLE_CONNECTOR_FAILURE',explanation:'The failure appears temporary. Wait briefly, then retry once with exponential backoff.',steps:['Check the provider status page.','Wait before retrying.','Use the same idempotency key for write operations.']},
  RENEWAL_REQUIRED:{title:'Reconnect the account',reasonCode:'CONNECTOR_AUTHORIZATION_EXPIRED',explanation:'The authorization appears expired or revoked.',steps:['Open the connector settings.','Start the official reauthorization flow.','Grant only the permissions the connector needs.']},
  PERMISSION_MISMATCH:{title:'Review the required permission',reasonCode:'CONNECTOR_PERMISSION_DENIED',explanation:'The account is connected, but a required permission or scope is missing.',steps:['Identify the operation that was denied.','Compare it with the granted scopes.','Add only the missing permission or choose a read-only alternative.']},
  UNKNOWN:{title:'Keep the diagnosis explicit',reasonCode:'UNRECOGNIZED_CONNECTOR_FAILURE',explanation:'These safe signals do not identify one known failure type.',steps:['Check the provider documentation.','Record the time and normalized status.','Escalate without sharing credentials or raw personal data.']}
};
const transient=new Set(['ECONNABORTED','ECONNREFUSED','ECONNRESET','EHOSTUNREACH','ENETUNREACH','ETIMEDOUT','RATE_LIMITED','TEMPORARILY_UNAVAILABLE','TIMEOUT']);
const renewal=new Set(['AUTH_EXPIRED','CONSENT_EXPIRED','INVALID_GRANT','REFRESH_TOKEN_EXPIRED','TOKEN_EXPIRED','UNAUTHORIZED']);
const permission=new Set(['ACCESS_DENIED','FORBIDDEN','INSUFFICIENT_PERMISSIONS','INSUFFICIENT_SCOPE','PERMISSION_DENIED']);
export function classify(input={}){const status=Number(input.status),code=String(input.code||'').trim().toUpperCase().replace(/[\s-]+/g,'_'),matches=[status===401||renewal.has(code)?'RENEWAL_REQUIRED':null,status===403||permission.has(code)?'PERMISSION_MISMATCH':null,status===408||status===425||status===429||(status>=500&&status<=599)||transient.has(code)?'TRANSIENT':null].filter(Boolean);return outcomes[matches.length===1?matches[0]:'UNKNOWN'];}
if(typeof document!=='undefined'){
  const form=document.querySelector('#diagnose-form'),result=document.querySelector('#result'),actions=document.querySelector('#result-actions'),copy=document.querySelector('#copy-result'),share=document.querySelector('#share-tool');let latest;
  form?.addEventListener('submit',event=>{event.preventDefault();try{const data=new FormData(form),diagnosis=classify({status:data.get('status'),code:data.get('code')});latest=diagnosis;result.innerHTML=`<p class="reason">${diagnosis.reasonCode}</p><h2>${diagnosis.title}</h2><p>${diagnosis.explanation}</p><ol>${diagnosis.steps.map(step=>`<li>${step}</li>`).join('')}</ol>`;result.hidden=false;actions.hidden=false;result.focus?.();}catch{result.textContent='The diagnosis could not be generated. Check the normalized status or error code and try again.';result.hidden=false;actions.hidden=true;}});
  copy?.addEventListener('click',async()=>{if(!latest)return;const text=`${latest.title}\n${latest.explanation}\n${latest.steps.map((step,index)=>`${index+1}. ${step}`).join('\n')}\n\nGenerated locally with Connector Recovery Guide`;try{await navigator.clipboard.writeText(text);copy.textContent='Copied';setTimeout(()=>{copy.textContent='Copy recovery steps'},1800);}catch{copy.textContent='Copy unavailable';}});
  share?.addEventListener('click',async()=>{const payload={title:'Connector Recovery Guide',text:'Private browser-only guidance for connector errors.',url:'https://ghostburst.github.io/connector-recovery-guide/'};try{if(navigator.share)await navigator.share(payload);else{await navigator.clipboard.writeText(payload.url);share.textContent='Link copied';setTimeout(()=>{share.textContent='Share this guide'},1800);}}catch(error){if(error?.name!=='AbortError')share.textContent='Share unavailable';}});
}
